### PR TITLE
Add linux and android support, add shared lib compilation, update to zig 0.11.0

### PR DESCRIPTION
**Pull request by Beyley**
Requiring the systemd submodule should allow cross compilation of a linux build from other platforms, but its untested

If the submodule is a no-no, then i can just add `/usr/include` as a library include path on linux

This also adds the logic to build both a shared and static library, and although i have been unable to get a dynamic windows build working, static builds work fine
Both shared and static work for linux builds
And i cant cross compile to MacOS seemingly, so thats untested for shared libs

### CODE REVIEW

**Comment by Beyley** [comment]
ah trying to actually dlopen it provides some errors, so im gonna mark this as draft for now
image

**Comment by Beyley** [comment]
So what i have so far is:
Linux native builds work (no cross compilation *to* linux yet, due to missing headers and libraries)

Cross compilation *to* macos works (if you provide your own [macos SDK](https://github.com/hexops/sdk-macos-12.0) in a path i search for [still needs to be handled better, hardcoded to `../system-sdk`]), but the resulting binaries are completely untested, all i know is that my game can compile for MacOS, link and create a *seemingly* good executable, but i have not tested it

Cross compilation to windows works, but linking against the resulting SDL causes `error: lld-link: __stack_chk_fail was replaced` (x86_64-windows-gnu target)

**Comment by Beyley** [comment]
I have tested this on all desktop platforms and have gotten working SDL libs on MacOS, Windows, and Linux, but still a WIP as i need to cleanup the MacOS cross-target code

**Comment by Beyley** [comment]
Android is now tested working

**Comment by Beyley** [comment]
I think this is ready for an initial review, this is tested working on Windows, MacOS, and Linux, and cross compilation should "just work" too, if you provide the build a valid Linux and MacOS SDK path (this is unneeded on windows luckily)

**Comment by Beyley** [comment]
updated fully to 0.11.0

**Comment by Beyley** [comment]
https://github.com/Beyley/ztyping/actions/runs/5781209317/job/15665993591
almost all cross compilation is now being actively tested in my game's CI, the only broken compilation is MacOS -> Linux which seems to be a compiler bug?

**Comment by rrohrer** [comment]
Any chance on getting this (or something like it) merged? It would be nice to have Linux builds working 👍

**Comment by Beyley** [comment]
> Any chance on getting this (or something like it) merged? It would be nice to have Linux builds working 👍 

frankly my code is a complete mess, im not sure how likely a merge is given it's state, i might close this PR since getting it mergable would be a herculean task im not able to do right now for time reasons, but my code *should* work as is (even in the package manager)

**Pull request closed without merging**
