### PR TITLE
Merge SDL 2.30.8

### PR DESCRIPTION
**Pull request by jayschwa**
Zig-specific source and header modifications have been retained. More specifically, I compared changes from commit ff9294a to f9637db.

I tested (native) Linux and Windows (via Wine) builds of VVVVVV and an unreleased personal project.

### CODE REVIEW

**Comment by jayschwa** [comment]
I have updated the branch / pull request to SDL 2.30.8. I re-tested with VVVVVV and my unreleased project.

**Comment by andrewrk** [comment]
@jayschwa can I interest you in maintainer status of this package? (not saying I won't help, I think these kind of packages can have many maintainers)

**Comment by jayschwa** [comment]
> @jayschwa can I interest you in maintainer status of this package? (not saying I won't help, I think these kind of packages can have many maintainers)

Sure. I've also got SDL_image and TTF library repos that I could bring into AYCB at some point. They probably need some cleanup first.

**Comment by andrewrk** [comment]
> TTF library

related: https://codeberg.org/andrewrk/TrueType/

**Comment by jayschwa** [comment]
@marler8997, you had some changes a couple weeks ago to fix / improve x86_64-windows-msvc support. Your changes should be preserved, but I'm not sure how to exercise them.

**Comment by jayschwa** [comment]
File modification summary between SDL 2.26.3 and this repo's main branch:

```
$ git diff --numstat --diff-filter=M release-2.26.3 allyourcodebase/main 
3       182     .gitignore
3       17      README.md
2       1       include/SDL_config_macosx.h
5       1       include/SDL_config_windows.h
0       3       include/SDL_cpuinfo.h
1       1       include/SDL_egl.h
1       1       include/SDL_opengles2.h
0       52      src/dynapi/SDL_dynapi.h
4       3       src/joystick/SDL_joystick.c
4       4       src/render/direct3d/SDL_render_d3d.c
```

File modification summary between SDL 2.30.8 and this pull request branch:

```
$ git diff --numstat --diff-filter=M release-2.30.8 zig-2.30.5
3       190     .gitignore
3       17      README.md
2       1       include/SDL_config_macosx.h
5       1       include/SDL_config_windows.h
0       3       include/SDL_cpuinfo.h
1       1       include/SDL_egl.h
1       1       include/SDL_opengles2.h
0       52      src/dynapi/SDL_dynapi.h
4       3       src/joystick/SDL_joystick.c
4       4       src/render/direct3d/SDL_render_d3d.c
```

**Comment by andrewrk** [comment]
IMO just go for it. Projects are already pinned to an earlier version that works for them, and if they find a problem when upgrading they can work to fix it before updating the dependency.

**Pull request merged**
