### PR TITLE
Update build.zig

### PR DESCRIPTION
**Pull request by david-vanderson**
On linux, SDL_config.h needs to be installed in the SDL2 subdir.

### CODE REVIEW

**Comment by marler8997** [comment]
> On linux, SDL_config.h needs to be installed in the SDL2 subdir.

Doesn't seem like it.  As you can see in this search: https://github.com/search?q=repo%3Aallyourcodebase%2FSDL%20SDL_config.h&type=code, the various header files include it via `#include "SDL_config.h"` meaning they expect it to exist at the root of one of the search paths.  The original CMake file configures it and installs it to a root include search path as well.  What makes you think it needs to be in an SDL2 subdir?  Maybe there's something else going on that I could help with?

**Comment by david-vanderson** [comment]
Thanks for looking at this!

I've made https://github.com/david-vanderson/SDLtest as a minimal reproduction.  When I run `zig build` on linux, it successfully compiles SDL, but fails compiling my zig code:
```
SDLtest$ zig build
install
└─ sdl-ontop
   └─ run sdl-ontop
      └─ compile-sdl-ontop
         └─ install sdl-ontop
            └─ zig build-exe sdl-ontop Debug native 2 errors
SDLBackend.zig:1:15: error: C import failed
pub const c = @cImport({
              ^~~~~~~~
referenced by:
    c: sdl-ontop.zig:3:21
    main: sdl-ontop.zig:9:9
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
/home/dvanderson/code/SDLtest/.zig-cache/o/7eedcdd83730a7847674a88b6d7755d5/SDL_config.h:33:10: error: 'SDL_platform.h' file not found
#include "SDL_platform.h"
         ^
error: the following command failed with 2 compilation errors:
/home/dvanderson/apps/zig-linux-x86_64-0.13.0/zig build-exe -ODebug --dep SDLBackend -Mroot=/home/dvanderson/code/SDLtest/sdl-ontop.zig /home/dvanderson/code/SDLtest/.zig-cache/o/2d38486868ab786727ece3353c72f974/libSDL2.a -ODebug -I /home/dvanderson/code/SDLtest/.zig-cache/o/7eedcdd83730a7847674a88b6d7755d5 -MSDLBackend=/home/dvanderson/code/SDLtest/SDLBackend.zig -lX11 -lXext -lpulse -lc --cache-dir /home/dvanderson/code/SDLtest/.zig-cache --global-cache-dir /home/dvanderson/.cache/zig --name sdl-ontop --listen=- 
Build Summary: 4/10 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ sdl-ontop transitive failure
   └─ run sdl-ontop transitive failure
      ├─ zig build-exe sdl-ontop Debug native 2 errors
      └─ compile-sdl-ontop transitive failure
         └─ install sdl-ontop transitive failure
            └─ zig build-exe sdl-ontop Debug native (+2 more reused dependencies)
error: the following build command failed with exit code 1:
/home/dvanderson/code/SDLtest/.zig-cache/o/8b73abe6d93286771423f6649c90db60/build /home/dvanderson/apps/zig-linux-x86_64-0.13.0/zig /home/dvanderson/code/SDLtest /home/dvanderson/code/SDLtest/.zig-cache /home/dvanderson/.cache/zig --seed 0x7d7f1aa9 -Z13e6cdfb987aea94
```

That's complaining about finding SDL_platform.h, but the only difference I could see between linux and mac (windows same as mac) is the location of SDL_config.h

On linux (I don't know why there are 2):
```
SDLtest$ find . -name "SDL_config.h"
./.zig-cache/o/ba855f4b76bb8396bc016da9d1a92a03/SDL_config.h
./.zig-cache/o/7eedcdd83730a7847674a88b6d7755d5/SDL_config.h
```

On mac (and windows):
```
SDLtest % find . -name "SDL_config.h"
./.zig-cache/o/88fabc9489f7e766db73e61052cbdeb9/SDL2/SDL_config.h 
```

So I changed where SDL_config.h was installed, and that worked (for me).

Am I going about this wrong?  Do you see the same thing?

**Comment by marler8997** [comment]
ah you know what now that I've gone back and looked at the original CMake file, it does look like they install it to the SDL2 subdirectory.  I guess this was working in my case because I was adding the underlying SDL2 subdirectory as an include path as well for the VVVVVV repository.  Anyway this change does seem to work, and no need for the extra comment about "I don't know"...it looks right to me. Feel free to amend commit to remove the comment and I'll merge.

P.S.  There are two `SDL_config.h` header files in the cache because one is the location where Zig writes the generated header file from the configuration file, and other is the "installation directory" where zig installs all the header files for other dependences to reference.  The second is just a copy of the first so they should be identical.

**Comment by david-vanderson** [comment]
Done.  That makes sense about the 2 copies - thanks!

**Comment by david-vanderson** [comment]
Thanks for helping me here, and for all of your effort to get this compiling on linux.  I appreciate it!

**Pull request merged**
